"""Generate paper-overleaf/numbers.tex (LaTeX macros) from audited result JSON. Numbers in the paper come only from here.

    python3 code/make_numbers.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
OUT = os.path.join(ROOT, "paper_artifacts", "numbers.tex")


def main():
    c1 = json.load(open(os.path.join(ROOT, "results", "c1.json")))
    tag = {"deepseek-v4.1-flash": "Ds", "glm-5.3": "Glm"}
    lines = ["% generated by code/make_numbers.py from results/*.json (c1, c1b, c2, c3, c3r, m3c, rq2, e3p, e4_replay, e5, fixed_grid_sim, eb_baselines, ec_compare) -- do not edit by hand"]
    for m, v in c1["models"].items():
        t = tag[m]
        n = v["units"]
        k_tr, k_cf = round(v["p_tool_return"] * n), round(v["p_config"] * n)
        lines += [f"\\newcommand{{\\cOne{t}Units}}{{{n}}}",
                  f"\\newcommand{{\\cOne{t}TrK}}{{{k_tr}}}",
                  f"\\newcommand{{\\cOne{t}CfK}}{{{k_cf}}}",
                  f"\\newcommand{{\\cOne{t}Tr}}{{{v['p_tool_return']:.3f}}}",
                  f"\\newcommand{{\\cOne{t}Cf}}{{{v['p_config']:.3f}}}",
                  f"\\newcommand{{\\cOne{t}Pooled}}{{{v['pooled']:.3f}}}"]
    c1b = json.load(open(os.path.join(ROOT, "results", "c1b.json")))
    for m, v in c1b["primary"].items():
        t = tag[m]
        lines += [f"\\newcommand{{\\cOneB{t}Units}}{{{v['units']}}}",
                  f"\\newcommand{{\\cOneB{t}TrK}}{{{v['tool_return']}}}",
                  f"\\newcommand{{\\cOneB{t}CfK}}{{{v['config']}}}",
                  f"\\newcommand{{\\cOneB{t}Tr}}{{{v['tool_return'] / v['units']:.3f}}}",
                  f"\\newcommand{{\\cOneB{t}Cf}}{{{v['config'] / v['units']:.3f}}}",
                  f"\\newcommand{{\\cOneB{t}Pooled}}{{{(v['tool_return'] + v['config']) / (2 * v['units']):.3f}}}"]
    goals = sorted({k.split("|")[1] for k in c1b["secondary"]})
    lines.append(f"\\newcommand{{\\cOneBGoals}}{{{len(goals)}}}")
    lines.append(f"\\newcommand{{\\cOneBBankingGoals}}{{{sum(g.startswith('banking/') for g in goals)}}}")
    lines.append(f"\\newcommand{{\\cOneVerdictModels}}{{{sum(v['h1_certified'] for v in c1['models'].values())}}}")
    lines += session_b_macros()
    lines += m3c_macros()
    lines += sim_macros()
    lines += c3_macros()
    lines += mc_macros()
    lines += ebec_macros()
    lines += c3r_macros()
    open(OUT, "w").write("\n".join(lines) + "\n")
    write_rq2_table()
    write_e4_e5_tables()
    write_panel_table()
    write_exec_table()
    write_eb_ec()
    print(OUT, len(lines) - 1, "macros")


def _r1_final(path, a):
    """R1 (ContrastCS + RC-mix) read once at N on a fixed design, tool_return minus config (Prop 5b)."""
    import fixed_design as FD
    from riskcert import ContrastCS
    out = {}
    for m, ds in FD.paired_units(FD._first_rows(path), "tool_return", "config").items():
        cs = ContrastCS(a)
        for x in ds:
            cs.update((x + 1) / 2, 0.5)  # (xa - xb + 1)/2 with xa - xb = x
        out[m] = cs.interval()
    return out


def m3c_macros():
    """M3c fixed-design certificates (results/m3c.json) and R1 at the final time on C1b."""
    m = json.load(open(os.path.join(ROOT, "results", "m3c.json")))
    g = m["C1b"]["glm-5.3"]
    sb = m["sessionB"]
    r1 = _r1_final(os.path.join(ROOT, "data", "confirm_c1b.jsonl"), 0.05 / 2)["glm-5.3"]
    return [f"\\newcommand{{\\cOneBGlmEbUpper}}{{{g['eb']['upper']:.3f}}}",
            f"\\newcommand{{\\cOneBGlmHoefUpper}}{{{g['hoeffding']['upper']:.3f}}}",
            f"\\newcommand{{\\cOneBGlmDelta}}{{{g['mean_delta']:.3f}}}",
            f"\\newcommand{{\\cOneBGlmRoneUpper}}{{{r1[1]:.3f}}}",
            f"\\newcommand{{\\sbEb}}{{{sb['certified_eb']}}}",
            f"\\newcommand{{\\sbHoef}}{{{sb['certified_hoeffding']}}}"]


def sim_macros():
    """results/fixed_grid_sim.json: max error per method and protocol class."""
    p = os.path.join(ROOT, "results", "fixed_grid_sim.json")
    if not os.path.exists(p):
        return []
    r = json.load(open(p))
    tag = {"R1-final": "RoneFin", "R1-any": "RoneAny", "R1'-final": "RonepFin", "R1'-any": "RonepAny", "R1'mix-final": "RonepMixFin", "R1'mix-any": "RonepMixAny", "EB-final": "EbFin"}
    out = [f"\\newcommand{{\\simReps}}{{{r['reps']}}}", f"\\newcommand{{\\simN}}{{{r['N']}}}"]
    for k, t in tag.items():
        for cls, f in (("Sorted", lambda x: x["protocol"] in ("fixed-desc", "fixed-asc")),
                       ("Perm", lambda x: x["protocol"] == "fixed-perm"), ("Iid", lambda x: x["protocol"] == "iid")):
            out.append(f"\\newcommand{{\\sim{t}{cls}}}{{{max(x.get(k, float("nan")) for x in r['rows'] if f(x)):.3f}}}")
    return out


def c3_macros():
    """results/c3.json (C3, preregistered 83bb385c); placeholders until it exists."""
    p = os.path.join(ROOT, "results", "c3.json")
    tag = {"qwen3-8b-local": "Qwen", "glm-5.3": "Glm", "gpt-5.4-nano-2026-03-17": "Nano", "deepseek-v4.1-flash": "Ds"}
    if not os.path.exists(p):
        out = ["\\newcommand{\\cThreePtwo}{??}"]
        for t in tag.values():
            out += [f"\\newcommand{{\\cThree{t}{x}}}{{??}}" for x in ("Rounds", "Sign", "TrK", "CfK", "Delta", "EbLo", "EbHi")]
        return out
    c = json.load(open(p))
    out = [f"\\newcommand{{\\cThreePtwo}}{{{'passed' if c['P2'] else 'failed'}}}"]
    marg = [min(abs(x) for x in v["r1p_interval"]) for v in c["models"].values() if v["decision"]]
    out += [f"\\newcommand{{\\cThreeMarginMin}}{{{min(marg):.3f}}}", f"\\newcommand{{\\cThreeMarginMax}}{{{max(marg):.3f}}}"]
    name = {">": "tool return", "<": "configuration", None: "undecided"}
    for m, t in tag.items():
        v = c["models"][m]
        n = v["rounds"]
        out += [f"\\newcommand{{\\cThree{t}Rounds}}{{{n}}}", f"\\newcommand{{\\cThree{t}Sign}}{{{name[v['decision']]}}}",
                f"\\newcommand{{\\cThree{t}TrK}}{{{round(v['asr_tool_return'][0] * n)}}}",
                f"\\newcommand{{\\cThree{t}CfK}}{{{round(v['asr_config'][0] * n)}}}",
                f"\\newcommand{{\\cThree{t}Delta}}{{{v['delta']:+.3f}}}",
                f"\\newcommand{{\\cThree{t}EbLo}}{{{v['eb_ci'][0]:+.3f}}}", f"\\newcommand{{\\cThree{t}EbHi}}{{{v['eb_ci'][1]:+.3f}}}",
                f"\\newcommand{{\\cThree{t}Pooled}}{{{v['asr_pooled'][0]:.3f}}}",
                f"\\newcommand{{\\cThree{t}DisTr}}{{{v['discordant_tr_only']}}}", f"\\newcommand{{\\cThree{t}DisCf}}{{{v['discordant_cfg_only']}}}"]
    return out


def session_b_macros():
    out = []
    c2 = json.load(open(os.path.join(ROOT, "results", "c2.json")))
    out += [f"\\newcommand{{\\cTwoK}}{{{c2['K']}}}", f"\\newcommand{{\\cTwoRone}}{{{c2['certified_r1']}}}",
            f"\\newcommand{{\\cTwoRonep}}{{{c2['certified_r1prime']}}}", f"\\newcommand{{\\cTwoAgree}}{{{c2['agree_with_A']}}}",
            f"\\newcommand{{\\cTwoModels}}{{{len({r['model'] for r in c2['rows']})}}}"]
    e = json.load(open(os.path.join(ROOT, "results", "e3p.json")))
    tag = {"R1": "Rone", "R1prime": "Ronep", "SPRT0.05": "SprtA", "SPRT0.01": "SprtB", "McNemar_peek": "Mcn", "Wilson_peek": "Wil"}
    for L, v in e["results"]["null"].items():
        for m, t in tag.items():
            out.append(f"\\newcommand{{\\eThree{t}L{ {'1': 'one', '5': 'five', '20': 'twenty'}[L] }}}{{{v[m]['fwer']:.3f}}}")
    out += [f"\\newcommand{{\\eThreeReps}}{{{e['reps']}}}", f"\\newcommand{{\\eThreeRounds}}{{{e['n_rounds']}}}"]
    r = json.load(open(os.path.join(ROOT, "results", "rq2.json")))
    ad = r["AgentDojo"]["within_session_A"]
    out.append("\\newcommand{\\rqTwoReps}{200}")  # sessb_analyze.rq2 default reps (preregistered run)
    out.append(f"\\newcommand{{\\rqTwoOursMisses}}{{{max(round(v['within_session_A'][m]['simultaneous_miss'] * 200) for v in r.values() for m in ('RC-mix', 'plug-in'))}}}")
    out += [f"\\newcommand{{\\rqTwoAdK}}{{{r['AgentDojo']['K']}}}", f"\\newcommand{{\\rqTwoIaK}}{{{r['InjecAgent ASR-valid']['K']}}}",
            f"\\newcommand{{\\rqTwoAdWilMiss}}{{{ad['Wilson-peek']['simultaneous_miss']:.3f}}}",
            f"\\newcommand{{\\rqTwoAdMixW}}{{{ad['RC-mix']['mean_final_width']:.2f}}}",
            f"\\newcommand{{\\rqTwoAdPlugW}}{{{ad['plug-in']['mean_final_width']:.2f}}}",
            f"\\newcommand{{\\rqTwoAdCpW}}{{{ad['CP-final']['mean_final_width']:.2f}}}"]
    out += m3b_macros()
    out += rq1_macros(c2)
    return out


FAMILY = {"gpt-4o-mini-2024-07-18": "OpenAI", "gpt-4.1-mini-2025-04-14": "OpenAI", "gpt-5.4-nano-2026-03-17": "OpenAI",
          "qwen25-7b-local": "Qwen", "qwen3-8b-local": "Qwen", "qwen3-32b-local": "Qwen", "llama31-8b-local": "Meta",
          "deepseek-v4.1-flash": "DeepSeek", "glm-5.3": "Zhipu"}


def rq1_macros(c2):
    """RQ1 from the preregistered session-B certification (results/c2.json, R1')."""
    p = {}
    for r in c2["rows"]:
        p.setdefault(r["model"], {})[r["a"]] = r["p_a"]
        p.setdefault(r["model"], {})[r["b"]] = r["p_b"]
    top = {m: max(v, key=v.get) for m, v in p.items()}
    by = {}
    for r in c2["rows"]:
        if r["r1p"] in (">", "<"):
            by.setdefault((r["a"], r["b"]), {})[r["model"]] = r["r1p"]
    within = cross = 0
    for ms in by.values():
        ups = [m for m, s in ms.items() if s == ">"]
        dns = [m for m, s in ms.items() if s == "<"]
        for u in ups:
            for d in dns:
                within += FAMILY[u] == FAMILY[d]
                cross += FAMILY[u] != FAMILY[d]
    return [f"\\newcommand{{\\rqOneTr}}{{{sum(v == 'tool_return' for v in top.values())}}}",
            f"\\newcommand{{\\rqOneCf}}{{{sum(v == 'config' for v in top.values())}}}",
            f"\\newcommand{{\\rqOneRev}}{{{within + cross}}}", f"\\newcommand{{\\rqOneRevWithin}}{{{within}}}"]


def m3b_macros():
    out = []
    e4p = os.path.join(ROOT, "results", "e4.json")
    if os.path.exists(e4p):
        parts = []
        for i in range(4):
            parts += json.load(open(os.path.join(ROOT, "results", f"e4_replay_{i}.json")))
        fw = max(a["fwer"] for t in parts for a in t["arms"].values())
        ratios = [t["arms"]["adversary"]["mean_cost"] / t["arms"]["cold"]["mean_cost"] for t in parts]
        out += [f"\\newcommand{{\\eFourMaxFwer}}{{{fw:.3f}}}", f"\\newcommand{{\\eFourTransitions}}{{{len(parts)}}}",
                f"\\newcommand{{\\eFourAdvMinPct}}{{{round((min(ratios) - 1) * 100)}}}",
                f"\\newcommand{{\\eFourAdvMaxPct}}{{{round((max(ratios) - 1) * 100)}}}",
                f"\\newcommand{{\\eFourReps}}{{{parts[0]['reps']}}}"]
    e5p = os.path.join(ROOT, "results", "e5.json")
    if os.path.exists(e5p):
        cells = json.load(open(e5p))["cells"].values()
        pool = [json.loads(l) for l in open(os.path.join(ROOT, "data", "e5_payload_pool.jsonl"))]
        fin = [c for c in cells if c["bound"] is not None and c["bound"] != "inf" and float(c["bound"]) < 1]
        cap = [c for c in cells if c not in fin]
        out += [f"\\newcommand{{\\eFiveCells}}{{{len(list(cells))}}}", f"\\newcommand{{\\eFiveStopped}}{{{len(fin)}}}",
                f"\\newcommand{{\\eFiveCapped}}{{{len(cap)}}}",
                f"\\newcommand{{\\eFiveBound}}{{{max(float(c['bound']) for c in fin):.2f}}}",
                f"\\newcommand{{\\eFiveMaxR}}{{{max(c['r'] for c in fin):.3f}}}",
                f"\\newcommand{{\\eFiveLimit}}{{{max(c['q_limit'] for c in fin):.3f}}}",
                f"\\newcommand{{\\eFiveStopMin}}{{{min(c['stop_n'] for c in fin)}}}",
                f"\\newcommand{{\\eFiveStopMax}}{{{max(c['stop_n'] for c in fin)}}}",
                f"\\newcommand{{\\eFiveRuleStopMin}}{{{min(c['rule50_stop'] for c in cells)}}}",
                f"\\newcommand{{\\eFiveRuleStopMax}}{{{max(c['rule50_stop'] for c in cells)}}}",
                f"\\newcommand{{\\eFiveRuleMaxR}}{{{max(c['rule50_r'] for c in cells):.3f}}}",
                f"\\newcommand{{\\eFivePoolEntries}}{{{len(pool)}}}",
                f"\\newcommand{{\\eFivePool}}{{{len({x['text'] for x in pool})}}}"]  # distinct payload texts
    bp = os.path.join(ROOT, "results", "e4_budget540.json")
    if os.path.exists(bp):  # exploratory, appendix only
        b = json.load(open(bp))["results"]
        n, q = b["gpt-5.4-nano-2026-03-17"], b["qwen3-32b-local"]
        out += [f"\\newcommand{{\\xLiveNanoMin}}{{{min(v['live_decided'] for v in n.values())}}}",
                f"\\newcommand{{\\xLiveNanoMax}}{{{max(v['live_decided'] for v in n.values())}}}",
                f"\\newcommand{{\\xReplayNanoMin}}{{{min(v['replay_mean_decided'] for v in n.values()):.1f}}}",
                f"\\newcommand{{\\xReplayNanoMax}}{{{max(v['replay_mean_decided'] for v in n.values()):.1f}}}",
                f"\\newcommand{{\\xLiveQwen}}{{{min(v['live_decided'] for v in q.values())}}}",
                f"\\newcommand{{\\xReplayQwen}}{{{min(v['replay_mean_decided'] for v in q.values()):.1f}}}"]
    return out


def write_rq2_table():
    """Coverage and width in one table (PM 2026-10-06). Generated; do not edit main.tex copies of these numbers."""
    r = json.load(open(os.path.join(ROOT, "results", "rq2.json")))
    names = {"RC-mix": "RiskCert, mixture bet (ours)", "plug-in": "RiskCert, plug-in bet (ours)",
             "Wilson-peek": "Wilson, read at every step", "CP-final": "Clopper--Pearson, read once at the end"}
    benches = [("AgentDojo", "AgentDojo"), ("InjecAgent ASR-valid", "InjecAgent valid"), ("InjecAgent ASR-all", "InjecAgent all")]
    rows = ["% generated by code/make_numbers.py from results/rq2.json -- do not edit by hand",
            "\\begin{tabular}{l" + "rr" * len(benches) + "}", "\\toprule",
            "& " + " & ".join(f"\\multicolumn{{2}}{{c}}{{{lab}}}" for _, lab in benches) + " \\\\",
            "Method & " + " & ".join("miss $\\downarrow$ & width $\\downarrow$" for _ in benches) + " \\\\", "\\midrule"]
    for m, lab in names.items():
        cells = []
        for b, _ in benches:
            w = r[b]["within_session_A"][m]
            cells += [f"{w['simultaneous_miss']:.3f}", f"{w['mean_final_width']:.2f}"]
        name = f"\\textbf{{{lab}}}" if "ours" in lab else lab
        rows.append(name + " & " + " & ".join(cells) + " \\\\")
    rows += ["\\bottomrule", "\\end{tabular}"]
    open(os.path.join(ROOT, "paper_artifacts", "tab_rq2.tex"), "w").write("\n".join(rows) + "\n")




NAME = {"gpt-4o-mini-2024-07-18": "GPT-4o-mini", "gpt-4.1-mini-2025-04-14": "GPT-4.1-mini", "gpt-5.4-nano-2026-03-17": "GPT-5.4-nano",
        "qwen25-7b-local": "Qwen2.5-7B", "qwen3-8b-local": "Qwen3-8B", "qwen3-32b-local": "Qwen3-32B", "glm-5.3": "GLM-5.3",
        "deepseek-v4.1-flash": "DeepSeek-V4.1-Flash"}
CHN = {"tool_return": "tool return", "config": "configuration", "tool_desc": "tool description"}


def write_e4_e5_tables():
    parts = []
    for i in range(4):
        parts += json.load(open(os.path.join(ROOT, "results", f"e4_replay_{i}.json")))
    rows = ["\\begin{tabular}{lrrrrr}", "\\toprule",
            "Transition & Cold $\\downarrow$ & Previous table $\\downarrow$ & Correct side $\\downarrow$ & Wrong side $\\downarrow$ & Max FWER $\\downarrow$ \\\\", "\\midrule"]
    for t in parts:
        a = t["arms"]
        rows.append(f"{NAME[t['prev']]} $\\to$ {NAME[t['new']]} & " + " & ".join(f"{a[k]['mean_cost']:.0f}" for k in ("cold", "prev", "oracle", "adversary"))
                    + f" & {max(a[k]['fwer'] for k in a):.3f} \\\\")
    rows += ["\\bottomrule", "\\end{tabular}"]
    open(os.path.join(ROOT, "paper_artifacts", "tab_e4.tex"), "w").write("\n".join(rows) + "\n")
    e5 = json.load(open(os.path.join(ROOT, "results", "e5.json")))["cells"]
    rows = ["\\begin{tabular}{llrrrrr}", "\\toprule",
            "Model & Channel, position & Stop & Species & New in 300 $\\downarrow$ & 50-run rule stop & 50-run rule rate $\\downarrow$ \\\\", "\\midrule"]
    for k, v in e5.items():
        m, ch, pos = k.split("__") if "__" in k else k.split("|")
        stop = str(v["stop_n"]) if v["bound"] is not None and str(v["bound"]) not in ("inf", "Infinity") and float(v["bound"]) < 1 else "cap"
        rows.append(f"{NAME.get(m, m)} & {CHN.get(ch, ch)}, {pos} & {stop} & {v['species_at_stop']} & {v['new_in_cont']} & "
                    f"{v['rule50_stop']} & {v['rule50_r']:.3f} \\\\")
    rows += ["\\bottomrule", "\\end{tabular}"]
    open(os.path.join(ROOT, "paper_artifacts", "tab_e5.tex"), "w").write("\n".join(rows) + "\n")


VENDOR = {"gpt": "OpenAI", "qwen": "Alibaba", "llama": "Meta", "deepseek": "DeepSeek", "glm": "Zhipu", "gemini": "Google",
          "claude": "Anthropic", "kimi": "Moonshot"}
NAME.update({"llama31-8b-local": "Llama-3.1-8B", "claude-haiku-4-5": "Claude-Haiku-4.5", "gemini-3.8-flash": "Gemini-3.8-Flash",
             "kimi-k3": "Kimi-K3"})


def write_panel_table():
    """Model panel: which experiment uses which model (from the raw rows of each experiment)."""
    import sessb_analyze as S
    ad_a, ad_b = {r["model"] for r in S.load_ad("A")}, {r["model"] for r in S.load_ad("B")}
    ia = {r["model"] for r in S.load_ia("A")}
    audit = {"qwen3-8b-local", "glm-5.3", "gpt-5.4-nano-2026-03-17", "deepseek-v4.1-flash"}
    chain = {m for t in E4_CHAINS for m in t}
    e5 = {k.split("__")[0] for k in json.load(open(os.path.join(ROOT, "results", "e5.json")))["cells"]}
    local = {"qwen3-8b-local", "llama31-8b-local", "qwen25-7b-local", "qwen3-32b-local"}
    ck = lambda b: "$\\checkmark$" if b else ""
    rows = ["\\begin{tabular}{llcccccc}", "\\toprule",
            "Model & Vendor & Weights & Grid A & Grid B & InjecAgent & Audit & Release chain \\\\", "\\midrule"]
    for m in sorted(ad_a | ia, key=lambda x: (next(v for k, v in VENDOR.items() if x.startswith(k)), NAME.get(x, x))):
        rows.append(f"{NAME.get(m, m)} & {next(v for k, v in VENDOR.items() if m.startswith(k))} & {'open' if m in local else 'API'} & "
                    f"{ck(m in ad_a)} & {ck(m in ad_b)} & {ck(m in ia)} & {ck(m in audit)} & {ck(m in chain)} \\\\")
    rows += ["\\bottomrule", "\\end{tabular}"]
    open(os.path.join(ROOT, "paper_artifacts", "tab_panel.tex"), "w").write("\n".join(rows) + "\n")


E4_CHAINS = (("gpt-4o-mini-2024-07-18", "gpt-4.1-mini-2025-04-14", "gpt-5.4-nano-2026-03-17"),
             ("qwen25-7b-local", "qwen3-8b-local", "qwen3-32b-local"))


def _cp_upper(k, n, a=0.05):
    from scipy.stats import beta
    return 1.0 if k == n else float(beta.ppf(1 - a / 2, k + 1, n - k))


def mc_macros():
    """Clopper-Pearson 95% upper ends for the Monte Carlo error rates quoted in the text (count = rate x replays)."""
    out = []
    r = json.load(open(os.path.join(ROOT, "results", "rq2.json")))
    k = max(round(v["within_session_A"][m]["simultaneous_miss"] * 200) for v in r.values() for m in ("RC-mix", "plug-in"))
    out.append(f"\\newcommand{{\\rqTwoMissUpper}}{{{_cp_upper(k, 200):.3f}}}")
    e = json.load(open(os.path.join(ROOT, "results", "e3p.json")))
    n = e["reps"]
    for m, t in (("R1", "Rone"), ("R1prime", "Ronep")):
        k = max(round(v[m]["fwer"] * n) for v in e["results"]["null"].values())
        out.append(f"\\newcommand{{\\eThree{t}Upper}}{{{_cp_upper(k, n):.3f}}}")
    f = json.load(open(os.path.join(ROOT, "results", "fixed_grid_sim.json")))
    k = max(round(x["R1-final"] * f["reps"]) for x in f["rows"])
    out.append(f"\\newcommand{{\\simRoneFinUpper}}{{{_cp_upper(k, f['reps']):.3f}}}")
    parts = []
    for i in range(4):
        parts += json.load(open(os.path.join(ROOT, "results", f"e4_replay_{i}.json")))
    k = max(round(t["arms"][a]["fwer"] * t["reps"]) for t in parts for a in t["arms"])
    out.append(f"\\newcommand{{\\eFourFwerUpper}}{{{_cp_upper(k, parts[0]['reps']):.3f}}}")
    return out


def write_exec_table():
    """Execution record: episodes and run window (SGT) per experiment, from the per-episode timestamps."""
    import datetime
    import glob
    import sessb_analyze as S

    def rows_of(paths):
        out = []
        for p in paths:
            out += [json.loads(l) for l in open(p)]
        return out

    D = os.path.join(ROOT, "data")
    groups = [("Discovery grid, session A (AgentDojo)", S.load_ad("A")), ("Discovery grid, session B (AgentDojo)", S.load_ad("B")),
              ("InjecAgent, sessions A and B", S.load_ia("A") + S.load_ia("B")),
              ("Confirmation on new goals (RQ1)", rows_of([os.path.join(D, "confirm_c1b.jsonl")])),
              ("Channel audit (RQ1)", rows_of(sorted(glob.glob(os.path.join(D, "c3_*.jsonl"))))),
              ("Replication of the channel audit (RQ1)", rows_of(sorted(glob.glob(os.path.join(D, "c3r_*.jsonl"))))),
              ("Discovery stop (RQ4)", rows_of(sorted(glob.glob(os.path.join(D, "e5_*__*.jsonl")))))]
    sgt = datetime.timezone(datetime.timedelta(hours=8))
    f = lambda t: datetime.datetime.fromtimestamp(float(t), sgt).strftime("%Y-%m-%d %H:%M")
    rows = ["\\begin{tabular}{lrl}", "\\toprule", "Experiment & Episodes & Run window (SGT) \\\\", "\\midrule"]
    for name, rs in groups:
        ts = [r["ts"] for r in rs if r.get("ts") is not None]
        win = f"{f(min(ts))} to {f(max(ts))}" if ts else "not recorded per episode"
        rows.append(f"{name} & {len(rs)} & {win} \\\\")
    rows += ["\\bottomrule", "\\end{tabular}"]
    open(os.path.join(ROOT, "paper_artifacts", "tab_exec.tex"), "w").write("\n".join(rows) + "\n")


def write_eb_ec():
    """E-B (contract-matched baselines) and E-C (Rank CS / BB-EDGE replay) tables; skipped until results exist."""
    pb = os.path.join(ROOT, "results", "eb_baselines.json")
    if os.path.exists(pb):
        d = json.load(open(pb))
        ms = ("sign (ours)", "alpha-spending OBF", "mSPRT", "fixed-n McNemar")
        rows = ["\\begin{tabular}{rr" + "rr" * len(ms) + "}", "\\toprule",
                " & & " + " & ".join(f"\\multicolumn{{2}}{{c}}{{{m.replace(' (ours)', '')}{' (ours)' if 'ours' in m else ''}}}" for m in ms) + " \\\\",
                "$\\pi$ & $q$ & " + " & ".join("Power $\\uparrow$ & Mean rounds $\\downarrow$" for _ in ms) + " \\\\", "\\midrule"]
        for r in d["rows"]:
            if r["q"] == 0.5:
                continue
            cells = []
            for m in ms:
                v = r["methods"][m]
                cells += [f"{v['power']:.3f}", f"{v['mean_episode_cost'] / 2:.0f}"]
            rows.append(f"{r['pi']} & {r['q']} & " + " & ".join(cells) + " \\\\")
        rows += ["\\bottomrule", "\\end{tabular}"]
        open(os.path.join(ROOT, "paper_artifacts", "tab_eb.tex"), "w").write("\n".join(rows) + "\n")
    pc = os.path.join(ROOT, "results", "ec_compare.json")
    if os.path.exists(pc):
        d = json.load(open(pc))
        rows = ["\\begin{tabular}{lrrrrrr}", "\\toprule",
                "Method & FWER real $\\downarrow$ & FWER null $\\downarrow$ & @100 $\\uparrow$ & @250 $\\uparrow$ & @500 $\\uparrow$ & @1000 $\\uparrow$ \\\\", "\\midrule"]
        for m in ("sign (ours)", "comparison (ours)", "Rank CS", "BB-EDGE"):
            re_, nu = d["settings"]["real"][m], d["settings"]["null"][m]
            name = m.replace("sign (ours)", "Sign certificate (ours)").replace("comparison (ours)", "Comparison (ours)")
            rows.append(f"{name} & {re_['fwer']:.3f} & {nu['fwer']:.3f} & " + " & ".join(f"{re_['correct_at'][str(t)] if str(t) in re_['correct_at'] else re_['correct_at'][t]:.1f}" for t in (100, 250, 500, 1000)) + " \\\\")
        rows += ["\\bottomrule", "\\end{tabular}"]
        open(os.path.join(ROOT, "paper_artifacts", "tab_ec.tex"), "w").write("\n".join(rows) + "\n")


def ebec_macros():
    out = []
    pb = os.path.join(ROOT, "results", "eb_baselines.json")
    if os.path.exists(pb):
        d = json.load(open(pb))
        r = {(x["pi"], x["q"]): x["methods"] for x in d["rows"]}
        nn = [x for x in d["rows"] if x["q"] != 0.5]
        out += [f"\\newcommand{{\\ebSignPowMid}}{{{r[(0.1, 0.8)]['sign (ours)']['power']:.2f}}}",
                f"\\newcommand{{\\ebObfPowMid}}{{{r[(0.1, 0.8)]['alpha-spending OBF']['power']:.2f}}}",
                f"\\newcommand{{\\ebSignLatBig}}{{{r[(0.35, 0.95)]['sign (ours)']['mean_episode_cost'] / 2:.0f}}}",
                f"\\newcommand{{\\ebObfLatBig}}{{{r[(0.35, 0.95)]['alpha-spending OBF']['mean_episode_cost'] / 2:.0f}}}",
                f"\\newcommand{{\\ebWins}}{{{sum(x['methods']['sign (ours)']['power'] >= x['methods']['alpha-spending OBF']['power'] for x in nn)}}}",
                f"\\newcommand{{\\ebNonNull}}{{{len(nn)}}}",
                f"\\newcommand{{\\ebMaxErr}}{{{max(v['error'] for x in d['rows'] for v in x['methods'].values()):.3f}}}",
                f"\\newcommand{{\\ebReps}}{{{d['reps']}}}"]
    pc = os.path.join(ROOT, "results", "ec_compare.json")
    if os.path.exists(pc):
        d = json.load(open(pc))["settings"]["real"]
        g = lambda m, t: d[m]["correct_at"][str(t)] if str(t) in d[m]["correct_at"] else d[m]["correct_at"][t]
        out += [f"\\newcommand{{\\ecSignHundred}}{{{g('sign (ours)', 100):.1f}}}", f"\\newcommand{{\\ecRankHundred}}{{{g('Rank CS', 100):.1f}}}",
                f"\\newcommand{{\\ecSignFiveH}}{{{g('sign (ours)', 500):.2f}}}", f"\\newcommand{{\\ecRankFiveH}}{{{g('Rank CS', 500):.2f}}}",
                f"\\newcommand{{\\ecBbFiveH}}{{{g('BB-EDGE', 500):.2f}}}",
                f"\\newcommand{{\\ecSignRound}}{{{d['sign (ours)']['mean_round_correct']:.0f}}}", f"\\newcommand{{\\ecRankRound}}{{{d['Rank CS']['mean_round_correct']:.0f}}}"]
    return out


def c3r_macros():
    p = os.path.join(ROOT, "results", "c3r.json")
    if not os.path.exists(p):
        return []
    c = json.load(open(p))
    tag = {"qwen3-8b-local": "Qwen", "glm-5.3": "Glm", "gpt-5.4-nano-2026-03-17": "Nano"}
    out = [f"\\newcommand{{\\cThreeRPtwo}}{{{'passed' if c['P2'] else 'failed'}}}"]
    for m, t in tag.items():
        v = c["models"][m]
        out += [f"\\newcommand{{\\cThreeR{t}Rounds}}{{{v['rounds']}}}",
                f"\\newcommand{{\\cThreeR{t}Same}}{{{'yes' if v['p1'] and v['decision'] else 'no'}}}"]
    return out

if __name__ == "__main__":
    main()
